services:
  booktrend-app:
    image: ryohei3364/booktrend-app:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - shared-net

networks:
  shared-net:
    external: true # 其他使用 external: true 的 docker-compose.yml 就可以加入這個網路