services:
  booktrend-app:
    image: ryohei3364/booktrend-app:${TAG}
    ports:
      - "3002:3000" # 測試環境，對外暴露3002，容器內仍是3000
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - shared-net

networks:
  shared-net:
    external: true # 其他使用 external: true 的 docker-compose.yml 就可以加入這個網路