services:
  booktrend-app:
    image: ryohei3364/booktrend:latest
    container_name: booktrend-app
    expose:
      - "3000"
    environment:
      - AWS_S3_KEY=${AWS_S3_KEY}
      - AWS_S3_SECRET=${AWS_S3_SECRET}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_RDS_USER=${AWS_RDS_USER}
      - AWS_RDS_PW=${AWS_RDS_PW}
      - AWS_RDS_HOST=${AWS_RDS_HOST}
      - AWS_RDS_DB=${AWS_RDS_DB}
      - AWS_RDS_PORT=${AWS_RDS_PORT}
    restart: unless-stopped
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - booktrend-app
    networks:
      - backend

networks:
  backend:
    driver: bridge