services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: booktrend-frontend
    ports:
      - "8080:80"   # 對外暴露 8080 端口，容器內 nginx 用 80
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: booktrend-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: on-failure
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: booktrend-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt:ro
      - ./nginx/ssl/private.key:/etc/nginx/ssl/private.key:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend

networks:
  backend:
    driver: bridge
